/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:826706:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:826706:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:685362:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:685362:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:478389:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton3:478389:

public void imgButton4_click1(GImageButton source, GEvent event) { //_CODE_:imgButton4:891949:
  println("imgButton4 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton4:891949:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  imgButton1 = new GImageButton(this, 812, 138, 296, 555, new String[] { "base.png", "base.png", "base.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 118, 110, 730, 80, new String[] { "heading.png", "heading.png", "heading.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 143, 430, 339, 262, new String[] { "direction.png", "direction.png", "direction.png" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  label1 = new GLabel(this, 409, 389, 145, 47);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Current Mode : 1");
  label1.setOpaque(true);
  imgButton4 = new GImageButton(this, 470, 431, 339, 262, new String[] { "direction1.png", "direction1.png", "direction1.png" } );
  imgButton4.addEventHandler(this, "imgButton4_click1");
  label2 = new GLabel(this, 614, 411, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Mode 2");
  label2.setOpaque(false);
  label3 = new GLabel(this, 253, 411, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Mode 1");
  label3.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
GLabel label1; 
GImageButton imgButton4; 
GLabel label2; 
GLabel label3; 